### PR TITLE
add API dev agreement

### PR DESCRIPTION
**Pull request by ktzhu**
Hello @majelbstoat, @kylehg, 

Please review the following commits I made in branch 'kt-dev-agreement'.

4615e0390179a5d2107dee7053715eb3bd90bfd7 (2015-10-07 12:05:23 -0700)
add API dev agreementg

R=@majelbstoat
R=@kylehg

MANUAL TESTING=not manually tested

### CODE REVIEW

**Comment by ktzhu** [comment]
do not merge until 5.30p

**Comment by sagudo** [comment]
lgtm! should @feerst publish his draft at 5:30 too?

**Comment by sagudo** [comment]
also let's link to the github version from the medium post

**Comment by ktzhu** [comment]
actually, feerst probably shouldn't publish on Medium until 6.30.

We are making GitHub things live at 5.30, "soft launch" – bc people are not likely sitting on github waiting for medium updates.

However, if we publish on Medium, esp in Policy, it will get distributed, and then kind of jump the gun on our announcement to the press at the event.

I've reflected this item in the [launch checklist for 2.0](https://github.com/Medium/launch-checklist/issues/34) – @feerst does that sound good?

**Comment by feerst** [comment]
Sure, Greg and I can wait til 6:30

On Wed, Oct 7, 2015 at 12:14 PM, kt <notifications@github.com> wrote:

> actually, feerst probably shouldn't publish on Medium until 6.30.
>
> We are making GitHub things live at 5.30, "soft launch" – bc people are
> not likely sitting on github waiting for medium updates.
>
> However, if we publish on Medium, esp in Policy, it will get distributed,
> and then kind of jump the gun on our announcement to the press at the event.
>
> I've reflected this item in the launch checklist for 2.0
> <https://github.com/Medium/launch-checklist/issues/34> – @feerst
> <https://github.com/feerst> does that sound good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medium/Policy/pull/12#issuecomment-146299767>.
>



-- 
Alex Feerst | Medium | feerst@medium.com <alex.feerst@medium.com> | @feerst
<https://medium.com/@feerst>

**Comment by ktzhu** [comment]
:pray: y'all rock

**Pull request merged**
