### PR TITLE
"steal" to "use" in README.md

### PR DESCRIPTION
**Pull request by aleksandar-todorovic**
It's not fair to refer to using CC-licensed content for other purposes as stealing, since the license itself is intended to allow others to use it.

### CODE REVIEW

**Comment by d2s** [comment]
:+1: Yes, this change would make sense, as (most?) Creative Commons licenses are clearly meant for enabling sharing of content. There are some differences in CC licenses (as some of them have more limits on how content can be used), but generally word `use` is better in this context.

More details:
- [About The Licenses - Creative Commons](https://creativecommons.org/licenses/)

- [Best practices for attribution - Creative Commons](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution)
  - Good examples on how people can show where the original content is from.
- [License Versions - Creative Commons](https://wiki.creativecommons.org/wiki/License_Versions) (more details

**Comment by mwichary** [comment]
…however, this introduces an awkward double appearance of “use” in one
sentence.

**Comment by sagudo** [comment]
Hi, to be clear - we were joking. We support free licenses and fair use, which is why we published these terms under a creative commons license. But a Github repo probably isn't the best place for irony, so to avoid future confusion I'll take the word steal out. Thanks for taking the time to read our terms!

**Comment by sagudo** [comment]
resolved by #18

**Pull request closed without merging**
